Make it easier to specify ECR images with docker plugin

diff --git a/hooks/command b/hooks/command
--- a/hooks/command
+++ b/hooks/command
@@ -365,10 +365,31 @@ if [[ "${BUILDKITE_PLUGIN_DOCKER_PROPAGATE_AWS_AUTH_TOKENS:-false}" =~ ^(true|on
   fi
 fi
 
+image="${BUILDKITE_PLUGIN_DOCKER_IMAGE}"
+# Handle ECR domain prefix
+if [[ -n "${BUILDKITE_PLUGIN_DOCKER_PREPEND_ECR_DOMAIN:-}" ]] ; then
+  ecr_region="${BUILDKITE_PLUGIN_DOCKER_ECR_REGION:-${AWS_DEFAULT_REGION:-}}"
+  if [[ -z $ecr_region ]]; then
+    echo "+++ 🚨 AWS region should be specified via plugin config or AWS_DEFAULT_REGION environment."
+    exit 1
+  fi
+
+  ecr_account_id="${BUILDKITE_PLUGIN_DOCKER_ECR_ACCOUNT_ID:-}"
+  if [[ -z $ecr_account_id ]]; then
+    ecr_account_id="$(aws sts get-caller-identity --query Account --output text)"
+  fi
+  if [[ -z $ecr_account_id ]]; then
+    echo >&2 "AWS account ID required via plugin config or 'aws sts get-caller-identity'"
+    exit 1
+  fi
+
+  image="${ecr_account_id}.dkr.ecr.${ecr_region}.amazonaws.com/${image}"
+fi
+
 if [[ "${BUILDKITE_PLUGIN_DOCKER_ALWAYS_PULL:-false}" =~ ^(true|on|1)$ ]] ; then
-  echo "--- :docker: Pulling ${BUILDKITE_PLUGIN_DOCKER_IMAGE}"
+  echo "--- :docker: Pulling ${image}"
   if ! retry "${BUILDKITE_PLUGIN_DOCKER_PULL_RETRIES:-3}" \
-       docker pull "${BUILDKITE_PLUGIN_DOCKER_IMAGE}" ; then
+       docker pull "${image}" ; then
     echo "!!! :docker: Pull failed."
     exit "$retry_exit_status"
   fi
@@ -487,7 +508,7 @@ fi
 args+=("--label" "com.buildkite.job-id=${BUILDKITE_JOB_ID}")
 
 # Add the image in before the shell and command
-args+=("${BUILDKITE_PLUGIN_DOCKER_IMAGE}")
+args+=("${image}")
 
 # Set a default shell if one is needed
 if [[ -z $shell_disabled ]] && [[ ${#shell[@]} -eq 0 ]] ; then
@@ -534,7 +555,7 @@ elif [[ ${#command[@]} -gt 0 ]] ; then
   done
 fi
 
-echo "--- :docker: Running command in ${BUILDKITE_PLUGIN_DOCKER_IMAGE}"
+echo "--- :docker: Running command in ${image}"
 echo -ne '\033[90m$\033[0m docker run ' >&2
 
 # Print all the arguments, with a space after, properly shell quoted
